### ISSUE TITLE
v0.9.0 does not build with Rust 1.80

### ISSUE THREAD

**Issue by teutat3s** [matrix-org/matrix-authentication-service#3088]
[alyssais discovered](https://github.com/NixOS/nixpkgs/issues/332957) that Rust 1.80.0 contains a couple of changes that break the build for `matrtix-authentication-service`. I'm opening this issue to coordinate efforts to make `matrtix-authentication-service` ready for 1.80.0.

Citing the linked issue:
> Figure out what's broken. Usually, but not always, this is that the "time" crate needs to be updated.

```
   Compiling time v0.3.34
error[E0282]: type annotations needed for `Box<_>`
```

It looks like the `time` crate was already bumped to `v0.3.36`, so all that would be needed here should be a new release.

**Comment by sandhose** [comment]
You're in luck, I plan to cut 0.10.0 RC later today, with the stable version coming up next week :)

**Comment by sandhose** [comment]
We just cut 0.10.0-rc.0, can you try upgrading to it and report back?

**Comment by teutat3s** [comment]
I can confirm `0.10.0-rc.0` builds fine with Rust 1.80.0.

**Comment by sandhose** [comment]
Alright, I'm closing this issue then, as we'll release 0.10.0 stable in the coming days, and you can start upgrading to 0.10.0-rc.0 in the meantime
